### ISSUE TITLE
Framework compatible

### ISSUE THREAD

**Issue by lucasvperini** [MHL1337/Fivem-Auto-Restart#1]
Hey!

Awesome resource!
It's compatible with a framework? Can you help me with that?
I want to announce on the chat when the server is going to restart.

Thank you!

**Comment by MHL1337** [comment]
Hi, i might create this in the future but for now its a no. Btw the file you downloaded is not working. I wrote a script wrong, so download the new one!

**Comment by lucasvperini** [comment]
Anyway for a announce?
Thanks.

**Comment by MHL1337** [comment]
Might create something like that in the future, but for now you'll have to create or find your own.
